apiVersion: v1
kind: Secret
metadata:
  name: github
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"

type: Opaque
data:
  access-token: Z2l0aHViX3BhdF8xMUE3MzJONEkwazF1NGNtZ25NZDdqX2lWVVZlVVRDN2gyZ1hGWkVXb1ZuMm1Na25KbUJYMlc0SjI0Uk9WclJaVnZXWFNMUzRNU2hNMENxZEYw
