apiVersion: v1
kind: Secret
metadata:
  name: merge-freeze
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"

type: Opaque
data:
  access-token: MzU1MDhiODAtZmVkYi00MjA2LWJhZDQtYzBkMzUwYWVkOTVl
