apiVersion: batch/v1
kind: Job
metadata:
  name: mergefreeze-freeze
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"

spec:
  template:
    spec:
      containers:
        - name: curl
          image: alpine/curl
          args:
            - -X
            - POST
            - https://www.mergefreeze.com/api/branches/dorianlangbeck/testing/main/?access_token=$(ACCESS_TOKEN)
            - -d
            - frozen=true&user_name=ArgoCD PreSync&note=Sync in progress
          env:
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: merge-freeze
                  key: access-token
      restartPolicy: Never
  backoffLimit: 2
