apiVersion: batch/v1
kind: Job
metadata:
  name: mergefreeze-freeze
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "100"

spec:
  template:
    spec:
      containers:
      - name: curl
        image: alpine/curl
        args:
          - -X
          - POST
          - https://www.mergefreeze.com/api/branches/dorianlangbeck/testing/main/?access_token=35508b80-fedb-4206-bad4-c0d350aed95e
          - -d
          - frozen=false&user_name=ArgoCD PostSync&note=Sync in completed

      restartPolicy: Never
  backoffLimit: 2
