apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # GitHub status check stuff
  - secrets/github-token.yaml
  - jobs/postsync-freeze.yaml
  - jobs/presync-freeze.yaml

  # Demo rollout stuff
  - rollouts/canary.yaml
  - services/canary.yaml
  - services/canary-preview.yaml
  - ingresses/canary.yaml
  - ingresses/canary-preview.yaml

images:
  - name: argoproj/rollouts-demo
    newTag: green
