apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # MergeFreeze stuff
  - secrets/mergefreeze.yaml
  - jobs/postsync-mergefreeze.yaml
  - jobs/presync-mergefreeze.yaml

  # Demo rollout stuff
  - rollouts/canary.yaml
  - services/canary.yaml
  - services/canary-preview.yaml
  - ingresses/canary.yaml
  - ingresses/canary-preview.yaml

images:
  - name: argoproj/rollouts-demo
    newTag: green
