apiVersion: batch/v1
kind: Job
metadata:
  name: mergefreeze-unfreeze
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "100"

spec:
  template:
    spec:
      containers:
        - name: curl
          image: alpine/curl
          command:
            - sh
            - -c
            - |
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $(ACCESS_TOKEN)"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/dorianlangbeck/testing/branches/main/protection/required_status_checks/contexts \
                -d '{"contexts":["ArgoCD - Sync in progress"]}'

          env:
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: merge-freeze
                  key: access-token
      restartPolicy: Never
  backoffLimit: 2
